### ISSUE TITLE
[问题]: 使用 kether 的 trmenu 私有动作 item matcher 语句做为判断时有出现报错情况。

### ISSUE THREAD

**Issue by Halogly** [CoderKuo/TrMenu#103]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2024-09-15 16:20:41)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Leaves-"e7c14b8" (MC: 1.20.4) (1.20.4-R0.1-SNAPSHOT)
| Java version: 21.0.3

| TrMenu: 3.3.3a
Installed Plugins: 
· Adyeshach - 2.0.17 (0 KB)
· AntiCreeper - 2.8 (0 KB)
· AntiPopup - 9.2 (0 KB)
· BKCommonLib - 1.20.6-v1 (0 KB)
· CMI - 9.7.5.5 (0 KB)
· CMILib - 1.5.1.3 (0 KB)
· Chemdah - 1.0.6 (0 KB)
· CoreProtect - 22.4 (0 KB)
· CustomJoinMessages - 17.6.0 (0 KB)
· Elevator - 3.13.0 (0 KB)
· GMusic - 1.0.0 (0 KB)
· HeadDatabase - 4.19.8 (0 KB)
· Images - 2.4.0 (0 KB)
· ItemEdit - 3.5.2 (0 KB)
· ItemJoin - 6.0.7-RELEASE-b995 (0 KB)
· ItemsAdder - 3.6.4-release-2 (0 KB)
· LegendaryGuild - 5.1.8.5 (0 KB)
· LiteSignIn - 1.8.2.0 (0 KB)
· LoneLibs - 1.0.56 (0 KB)
· LuckPerms - 5.4.137 (0 KB)
· NBTAPI - 2.13.0 (0 KB)
· NametagEdit - 4.5.23 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlayerPoints - 3.2.7 (0 KB)
· PlugManX - 2.4.1 (0 KB)
· ProtocolLib - 5.2.0-SNAPSHOT-679 (0 KB)
· ServerBackup - 2.10.0 (0 KB)
· TAB-Bridge - 5.0.7 (0 KB)
· TrChat - 2.1.0 (0 KB)
· TrMenu - 3.3.3a (0 KB)
· Train_Carts - 1.21-v1-SNAPSHOT (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· WorldEdit - 7.3.6+6892-3d660b8 (0 KB)
· dynmap - 3.7-SNAPSHOT-948 (0 KB)
· floodgate - 2.2.3-SNAPSHOT (b109-49bd564) (0 KB)
· voicechat - 2.5.16 (0 KB)

### 🔍 详细的描述

```
1. 新建一个带有 Custom Model Data 的物品，比如一部手机，原物品为纸，cmd值为 10（为了方便书写，将值假设为 10，可能会与日志信息不一致，原数据值为 1010001）。

2. 在 trmenu 的`settings.yml`文件的`RegisterCommands`中注册菜单指令这样写：

`RegisterCommands:
  openmenu:
    permission: null
    execute:
      - 'tell: &e需要填写面板名称!'
    arguments:
      phone: 
      - condition: item "material:paper,ModelData:10"
        actions: 
          - 'open: phone'
        deny:
          - 'message: &c你需要一部手机.'`

注册了一条指令 /openmenu phone，条件为玩家背包上是否有为 paper 且 cmd 数据值为 10 的物品。

3. 当玩家身上携带有指定物品时，正常打开菜单（物品绑定了注册的指令）；当玩家身上不携带该物品时，输入该注册的指令，出现报错，显示：
`An internal error occurred while attempting to perform this command`

4. 当身上不携带该物品时输入该注册的指令，后台红字，首行显示错误，输出 null。
```

### 🗄 服务端日志

```
[latest.log](https://github.com/user-attachments/files/17005095/latest.log)
关键位置：https://mclo.gs/ksmacsk
```

### ⚙ 配置文件

```
RegisterCommands:
  openmenu:
    permission: null
    execute:
      - 'tell: &e需要填写面板名称!'
    arguments:
      phone: 
      #- condition: inventory hand is "minecraft:paper[model=1010001]"
      - condition: item "material:paper,ModelData:1010001"
        actions: 
          - 'open: phone'
          - 'sound: BLOCK_NOTE_BLOCK_HAT-2-2'
        deny:
          - 'sound: ENTITY_ITEM_BREAK-1-0'
          - 'message: &c你需要一部手机.'
```
