### ISSUE TITLE
[问题]: refresh动作无法正常刷新图标

### ISSUE THREAD

**Issue by Sharrkkunjang** [CoderKuo/TrMenu#143]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2025-02-03 23:59:10)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Paper-424 (MC: 1.20.4) (1.20.4-R0.1-SNAPSHOT)
| Java version: 21

| TrMenu: 3.3.8
Installed Plugins: 
· AriKeys - 3.1 (0 KB)
· AttributePlus - 3.3.3.0 (0 KB)
· Atziluth - 2.0.55 (0 KB)
· BetterHud - 1.11.4 (0 KB)
· Essentials - 2.21.0-dev+154-667b0f7 (0 KB)
· FastAsyncWorldEdit - 2.9.2 (0 KB)
· Gunging_Ootilities_Plugin - 1.10.9 (0 KB)
· KetherFactory - 1.0.0 (0 KB)
· LibsDisguises - 10.0.44-SNAPSHOT (0 KB)
· ModelEngine - R4.0.8 (0 KB)
· MythicCrucible - 2.2.0-SNAPSHOT (0 KB)
· MythicMobs - 5.8.0-SNAPSHOT-b5f60c44 (0 KB)
· MythicVariable - 1.0.2 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· ProtocolLib - 5.3.0 (0 KB)
· ProtocolStringReplacer - 3.1.1 (0 KB)
· RocketPlaceholders - 2.3.1 (0 KB)
· SharrkExtension - 1.0 (0 KB)
· TrMenu - 3.3.8 (0 KB)
· UUIDToIntArray - 1.0.0 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· WorldGuard - 7.0.9+5934e49 (0 KB)
· Yetzirah - 1.0.42 (0 KB)
· packetevents - 2.7.0 (0 KB)

### 🔍 详细的描述

refresh动作无效, 但是refresh选项有效, 我是更新到最新版才碰到这问题的
```yaml
 BUTTONS:
 '1'
  refresh: 20 #自动刷新, 这是有效的
 display:
  mat: diamond
 actions:
  all:
  - refresh #这是无效的
  - update #也试了这个
```

### 🗄 服务端日志

[latest.log](https://github.com/user-attachments/files/18644830/latest.log)

### ⚙ 配置文件

```yaml
 '4':
  refresh: 10
  display:
   mats: iron_ingot
   name: '&e%yetzirah_class:skill-by-index:4:display:name% &7&oLv.&r&7%yetzirah_class:skill-by-index:4:level%&a ➠ &7%math_0_1+{yetzirah_class:skill-by-index:4:level}%'
   lore:
   - ' '
   - '%yetzirah_class:skill-by-index:4:display:description%'
   - '  %changeoutput_>=_input:{yetzirah_class:level}_matcher:{yetzirah_class:skill-by-index:4:context:等级需求}_ifmatch:&a✔_else:&c✘% %yetzirah_class:skill-by-index:4:context:等级需求% &7职业等级'
   - '  %changeoutput_>=_input:{yetzirah_class:points}_matcher:{yetzirah_class:skill-by-index:4:context:升级点数}_ifmatch:&a✔_else:&c✘% %yetzirah_class:skill-by-index:4:context:升级点数% &7技能点数'
  actions:
   all:
   - condition: 'check papi *%yetzirah_class:skill-by-index:4:level% > *0'
     actions:
     - condition: 'check papi *%math_{yetzirah_class:level}<{yetzirah_class:skill-by-index:4:context:等级需求}% == *0'
       actions:
       - condition: 'check papi *%math_{yetzirah_class:points}<{yetzirah_class:skill-by-index:4:context:升级点数}% == *0'
         actions:
         - 'console: yzr skill tryupgrade %player_name% %yetzirah_class:skill-by-index:4:name% true'
         - 'update'
         - 'refresh'
         deny:
         - 'close'
         - 'title: &c&l点数不足！'
       deny:
       - 'close'
       - 'title: &c&l等级不足！'
  icons:
  - condition: check papi *%yetzirah_class:skill-by-index:4:context:升级点数% == *null
    prioriry: 1
    inherit: true
    display:
     mat: barrier
     name: '&c'
     lore:
     - '&c无技能'
  - condition: check papi *%yetzirah_class:skill-by-index:4:level% == *0
    prioriry: 1
    inherit: true
    display:
     mat: gunpowder
     name: '&f%yetzirah_class:skill-by-index:4:display:name% &f[&c未学习&f]'
     lore:
     - ' '
     - '%yetzirah_class:skill-by-index:4:display:description%'
     - '  %changeoutput_>=_input:{yetzirah_class:level}_matcher:{yetzirah_class:skill-by-index:4:context:等级需求}_ifmatch:&a✔_else:&c✘% %yetzirah_class:skill-by-index:4:context:等级需求% &7职业等级'
     - '  %changeoutput_>=_input:{yetzirah_class:points}_matcher:{yetzirah_class:skill-by-index:4:context:学习点数}_ifmatch:&a✔_else:&c✘% %yetzirah_class:skill-by-index:4:context:学习点数% &7技能点数'
    actions:
     all:
     - condition: 'check papi *%math_0_{yetzirah_class:level}<{yetzirah_class:skill-by-index:4:context:等级需求}% == *0'
       actions:
       - condition: 'check papi *%math_{yetzirah_class:points}>={yetzirah_class:skill-by-index:4:context:学习点数}% == *0'
         actions:
         - 'close'
         - 'title: &c&l点数不足！'
         deny:
         - 'console: yzr skill study %player_name% main %yetzirah_class:skill-by-index:4:name%'
         - 'update'
         - 'refresh'
         - 'title: &c&l学习成功 %yetzirah_class:skill-by-index:4:name%！'
       deny:
       - 'close'
       - 'title: &c&l等级不足！'

  - condition: check papi *%math_0_{yetzirah_class:skill-by-index:4:level}>={yetzirah_class:skill-by-index:4:max-level}% == *1
    prioriry: 1
    inherit: true
    display:
     mat: golden_apple
     name: '&e%yetzirah_class:skill-by-index:4:display:name% &6&oLv.MAX'
     lore:
     - ' '
     - '%yetzirah_class:skill-by-index:4:display:description%'
```
