### ISSUE TITLE
[问题]: 物品可以拿出来 虽然是虚拟的

### ISSUE THREAD

**Issue by addpromax** [CoderKuo/TrMenu#152]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2025-03-01 14:52:57)

| Server OS: Windows Server 2022 amd64 10.0
| Server software: 1.21.4-2398-196c176 (MC: 1.21.4) (1.21.4-R0.1-SNAPSHOT)
| Java version: 22.0.2

| TrMenu: 3.4.0
Installed Plugins: 
· AdvancedAchievements - 7.2.0 (0 KB)
· AdvancedChests - 42.1 (0 KB)
· Aiyatsbus - 1.0.0-RC (0 KB)
· AiyatsbusLibreforge - 1.0.2 (0 KB)
· AlonsoTags - 2.2.1-BETA-PRO (0 KB)
· AngelChest - 13.9.4 (0 KB)
· AntiPopup - 10.1 (0 KB)
· BalancedVillagerTrades - 2.0-beta8 (0 KB)
· BeaconPlus3 - 3.0.92 (0 KB)
· BestTools - 2.2.1 (0 KB)
· BetterFarming - 5.9.7 (0 KB)
· BetterRTP - 3.6.13 (0 KB)
· BetterStructures - 1.7.8 (0 KB)
· BetterTridents - 2.2.6 (0 KB)
· ChestProtect - 5.20.5 (0 KB)
· ChestSort - 14.1.0 (0 KB)
· Citizens - 2.0.37-SNAPSHOT (build 3716) (0 KB)
· CoinsEngine - 2.3.4 (0 KB)
· CombatPets - 2.3.2 (0 KB)
· CommunityQuests - 2.11.5 (0 KB)
· ComplexTurrets - 3.17.2 (0 KB)
· CoreProtect - 22.4 (0 KB)
· CraftItem - 1.2.8 (0 KB)
· CtOnlineReward - 0.2.6 (0 KB)
· CustomCrafting - 4.16.11 (0 KB)
· Dantiao - EX-50 (0 KB)
· DeathMessages - 1.4.20 (0 KB)
· DecentHolograms - 2.8.15 (0 KB)
· DoorsReloaded - 1.3.1 (0 KB)
· DreamCleaner - 1.1.7-SNAPSHOT (0 KB)
· EcoQuests - 1.36.0 (0 KB)
· EconomyBridge - 1.2.0 (0 KB)
· EnchantmentSlots - 4.3.0 (0 KB)
· ExcellentCrates - 6.0.1 (0 KB)
· ExcellentJobs - 1.8.0 (0 KB)
· ExcellentShop - 4.14.0 (0 KB)
· FastAsyncWorldEdit - 2.12.4-SNAPSHOT-1050;0a0ea67 (0 KB)
· HuskHomes - 4.5.3 (0 KB)
· Insights - 6.19.1 (0 KB)
· InvSeePlusPlus - 0.29.18-SNAPSHOT (0 KB)
· InventoryRollbackPlus - 1.6.21 (0 KB)
· Lands - 7.12.4 (0 KB)
· LevelledMobs - 4.2.0.2 b98 (0 KB)
· LibreLogin - 0.24.0 (0 KB)
· LiteFarm - 3.2.5 (0 KB)
· LiteFish - 4.12.0 (0 KB)
· LiteMatter - 1.7.0 (0 KB)
· LiteSignIn - 1.8.4.2 (0 KB)
· Lootin - 11.3 (0 KB)
· Lottery - 1.4.9 (0 KB)
· LuckPerms - 5.4.131 (0 KB)
· LumberJack - 5.3.0 (0 KB)
· MMOCore - 1.13.1-SNAPSHOT (0 KB)
· MMOInventory - 1.9.1-SNAPSHOT (0 KB)
· MMOItems - 6.10.1-SNAPSHOT-ZH.dev.1.0.4 (0 KB)
· Maintenance - 4.2.1 (0 KB)
· McmmoGuiV2 - 2.2.0-BETA (0 KB)
· MiniMOTD - 2.1.2 (0 KB)
· Multiverse-Core - 4.3.15-SNAPSHOT (0 KB)
· MythicLib - 1.7.1-SNAPSHOT (0 KB)
· NBTAPI - 2.14.1 (0 KB)
· NerfPhantoms - 1.4.0 (0 KB)
· Nexo - 1.1-dev (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlayerInv - 4.14.62 (0 KB)
· PlayerParticles - 8.6 (0 KB)
· PlayerPoints - 3.3.0 (0 KB)
· ProtocolLib - 5.4.0-SNAPSHOT-741 (0 KB)
· PvPManager - 3.37 (0 KB)
· PyroLib - 1.4.2 (0 KB)
· PyroMining - 4.4.4 (0 KB)
· PyroWeatherPro - 4.3.1 (0 KB)
· Rankup - 3.15.1 (0 KB)
· SafariNet - 1.16.14-SNAPSHOT (0 KB)
· SakuraBind - 2.4.4 (0 KB)
· ShiftHotkey - 1.0.3 (0 KB)
· SkinsRestorer - 15.5.3 (0 KB)
· StaffSpectate - 4.2 (0 KB)
· SunLight - 3.12.6 (0 KB)
· SweetMail - 1.0.0-unstable (0 KB)
· TrMenu - 3.4.0 (0 KB)
· TradeSystem - 2.6.3 (0 KB)
· UpgradeableHoppers - 4.18.2 (0 KB)
· UpgradeableSpawners - 4.15.3 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· WolfyUtilities - 4.17-beta.7 (0 KB)
· WorldGuard - 7.0.13+82fdc65 (0 KB)
· XConomy - 2.26.3 (0 KB)
· ajLeaderboards - 2.9.0 (0 KB)
· eBackup - 1.3.0 (0 KB)
· eco - 6.75.2 (0 KB)
· libreforge - 4.71.6 (0 KB)
· mcMMO - 2.2.031 (0 KB)
· nightcore - 2.7.3.4 (0 KB)
· packetevents - 2.7.0 (0 KB)
· sleep-most - 5.5.3 (0 KB)

### 🔍 详细的描述

1.随便建立一个菜单
2.就这样了

https://github.com/user-attachments/assets/c3b84518-068b-4fff-8e07-84d95ce97652

### 🗄 服务端日志

```
无
```

### ⚙ 配置文件

```
#
# TrMenuV2 整体结构如下:
#
# 菜单的标题, 支持动态标题周期切换
#
title:
  - '菜单标题'
  - '第二个菜单标题'
#
# 若有多个标题, 切换的周期 (ticks)
#
title-update: 40



#
# 菜单的布局功能
# 你可以用 ` ` 来标记设置多个字符名称图标的位置
#
# 单页布局
shape:
  - '####`Head`####'
  - '         '
  - '         '
  - '         '
  - '#########'
#
# 多页布局
#
# shape:
#   - - '####`Head`####'
#     - '         '
#     - '         '
#     - '         '
#     - '########`Next`'
#   - - '####`Head`####'
#     - '         '
#     - '         '
#     - '         '
#     - '`Pre`########'
#



#
# 菜单的图标
#
buttons:
#
  # 图标的唯一 ID, 可配合布局使用
  # '#':
    # 显示图标的动态更新周期, 若设置多个则依次对应为 Material, Name, Lore, Slots
    # 设置一个即为所有项相同更新周期
    # update: [-1, 10, 15, -1]
    # 菜单的显示部分
    # display:
      # material: 'Gray Stained Glass Pane'
      # name: ['&fTr&7Menu', '&7Tr&8Menu', '&8Tr&0Menu','&7Tr&8Menu']
      # lore:
        # - - '&7Thanks &f:> &7for using!'
        # - - '&7Thanks &f:) &7for using!'
    # 点击菜单后执行的动作
    # actions:
      # all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
#
  '#':
    update: [-1, 10, 15, -1]
    display:
      material: 'Gray Stained Glass Pane'
      name: 
        - '&3公益&b配置'
        - '&b公益&3配置'
      lore:
        - - '&7感谢使用 公益配置2.2版本'
          - '&7感谢使用 公益配置2.2版本'
        - - '&7感谢使用 公益配置2.2版本'
    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
  'Head':
    display:
      mats: 'player head'
      name: ' %player_name% 的头'
      lore:
        - '生命值: ${health}'
        
        
        
#####################################################################################################################
#
# 以上为所有菜单 必须填入 的内容
#
# 以下为所有菜单 选择填入 的内容
#
#####################################################################################################################



#
# 菜单的选项设置
#
Options:
  # 是否启用菜单传参功能 （默认开启）
  Arguments: true
  # 默认填充参数
  Default-Arguments: ["0"]
  # 默认布局页码
  Default-Layout: 0
  # 是否隐藏玩家容器
  Hide-Player-Inventory: true
  # 防频繁点击的间隔
  Min-Click-Delay: 200
  # 强制需要依赖的 PlaceholderAPI 拓展变量
  #输入/papi ecloud download [Expansion] 
  #若服务端内下载失败
  #可使用链接 https://api.extendedclip.com/expansions/[Expansion]  [Expansion] 替换对应变量的英文名称
  #下载后安装至 服务端\plugins\PlaceholderAPI\expansions
  #完成后输入/papi reload
  Depend-Expansions:
    - 'player'
    
    
    
#
# 菜单绑定的快捷打开方式
#
Bindings:
  Commands:
    # 绑定命令支持正则匹配，例如添加 (?i) 前缀可以忽略大小写
    - '(?i)cd(-)?(gui)?(s)?'
  Items:
    # 物品特征，clock 适用于1.13+
    # 1.8-1.12请使用 watch
    # 了解绑定 物品特征 的详细写法，请打开下面链接
    # https://trmenu.trixey.cc/v/chinese/functions/item-identifiers
    - 'material:clock'
    - 'material:DIAMOND,name:公益配置V3'
    
    
    
#
# 菜单的事件处理
#
Events:
  # 开启菜单事件
  # 关闭菜单事件
  Close:
    - 'sound: BLOCK_CHEST_CLOSE-1-0'
    
    
    
#
# 菜单自定义周期性任务
#
Tasks:
  # 任务 Id
  tikTok:
    # 周期 ( Ticks )
    period: 20
    # 反应
    task:
      actions:
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-2'
        
        
        
#
# 菜单内置的自定义脚本变量
# 通过 ${ID_参数_参数} 的方式可以调用
# 需要有JavaScript基础，不做教程
#
Functions:
  health: |-
    function math(){
      return player.getHealth()
    }
    math()
    
    

#
# 更多详细内容请查看 公益配置V2.1 菜单配置
```
