### ISSUE TITLE
[问题]: 菜单物品使用NBT会导致无法加载菜单

### ISSUE THREAD

**Issue by TATyKeFei** [CoderKuo/TrMenu#162]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2025-04-07 19:22:04)

| Server OS: Linux amd64 6.11.0-19-generic
| Server software: 1.21.4-2412-9249a2c (MC: 1.21.4) (1.21.4-R0.1-SNAPSHOT)
| Java version: 21.0.5

| TrMenu: 3.4.3
Installed Plugins: 
· BKCommonLib - 1.21.4-v1-SNAPSHOT (0 KB)
· BetterHud - 1.12 (0 KB)
· CarbonChat - 3.0.0-beta.28 (0 KB)
· Citizens - 2.0.37-SNAPSHOT (build Unknown) (0 KB)
· CraftEngine - 0.0.45 (0 KB)
· CustomCrops - 3.6.32.3 (0 KB)
· CustomFishing - 2.3.6 (0 KB)
· CustomNameplates - 3.0.25 (0 KB)
· DecentHolograms - 2.8.15 (0 KB)
· DivineDrop - 2.16 (0 KB)
· EconomyShopGUI - 6.12.0 (0 KB)
· FastAsyncWorldEdit - 2.13.1-SNAPSHOT-1071;fc83763 (0 KB)
· InvSeePlusPlus - 0.29.20 (0 KB)
· IpacWhitelist - 4.1.1-rc1 (0 KB)
· JukeBox - 1.20.13 (0 KB)
· Lands - 7.13.1 (0 KB)
· LiteSignIn - 1.8.4.2 (0 KB)
· LuckPerms - 5.4.157 (0 KB)
· MHDF-Tools - 3.0.17 (0 KB)
· ModelEngine - R4.0.8 (0 KB)
· My_Worlds - 1.21.4-v1-SNAPSHOT (0 KB)
· MythicMobs - 5.8.1-SNAPSHOT-43d0350e (0 KB)
· NBTAPI - 2.14.1 (0 KB)
· NoteBlockAPI - 1.6.3 (0 KB)
· PAPIAnimations - ${project.version} (0 KB)
· PistonMOTD - 5.2.0 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlugManX - 2.4.1 (0 KB)
· ProtocolLib - 5.4.0-SNAPSHOT-742 (0 KB)
· RayTraceAntiXray - 1.16.1 (0 KB)
· ShopGUIPlus - 1.103.0 (0 KB)
· Skyline - 2.1.8 (0 KB)
· SweetMail - 1.0.0-unstable (0 KB)
· TAB - 5.0.7 (0 KB)
· TheSearch - 2.2.1 (0 KB)
· Tooltips - 2.4 (0 KB)
· TrMenu - 3.4.3 (0 KB)
· Typewriter - 0.8.0-beta-154 (0 KB)
· UltraBoomerangs - 1.1.8 (0 KB)
· UserPrefix - 3.2.6 (0 KB)
· Vault - 2.10.0 (0 KB)
· VeinMiner - 2.2.6 (0 KB)
· Vulcan - 2.9.5 (0 KB)
· WorldGuard - 7.0.13+82fdc65 (0 KB)
· packetevents - 2.7.0 (0 KB)
· untitled1 - 1.0-SNAPSHOT (0 KB)

### 🔍 详细的描述

```
1. 菜单物品使用NBT后无法加载菜单，把NBT部分注释掉后才能加载
```

### 🗄 服务端日志

```
[19:09:30 INFO]: TATyKeFei issued server command: /trmenu reload
[19:09:30 INFO]: [TrMenu] Error | An error occurred while loading the trplugins.menu phone ! Located at: MENU
[19:09:30 INFO]:     java.lang.reflect.InvocationTargetException
```

### ⚙ 配置文件

```
Title:
  - "%shift_mm_13%<image_gui_phone:1:1>"

Layout:
  - "##H######"
  - "#########"
  - "#########"
  "H":
    display:
      material: "head:%player_name%"
      nbt:
        CustomModelData: 10000
      name: §f%player_name%
      lore:
        - ""
        - "<white>点击打开个人资料"
    actions:
      all:
        - "command: profiles"
```
