### ISSUE TITLE
[问题]: 渐变文本不生效/异常

### ISSUE THREAD

**Issue by dodo939** [CoderKuo/TrMenu#176]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2025-05-31 12:23:42)

| Server OS: Windows 11 amd64 10.0
| Server software: 1.21.4-2408-5d1df70 (MC: 1.21.4) (1.21.4-R0.1-SNAPSHOT)
| Java version: 21.0.7

| TrMenu: 3.6.1
Installed Plugins: 
· CMI - 9.7.8.3 (0 KB)
· CMILib - 1.5.4.3 (0 KB)
· ExcellentEnchants - 4.3.3 (0 KB)
· ItemsAdder - 4.0.8 (0 KB)
· LiteSignIn - 1.8.2.0 (0 KB)
· LoneLibs - 1.0.63 (0 KB)
· LuckPerms - 5.4.164 (0 KB)
· MMOItems - 6.10.1-SNAPSHOT-ZH.dev.1.0.4 (0 KB)
· MythicLib - 1.7.1-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlayerPoints - 3.3.2 (0 KB)
· ProtocolLib - 5.4.0-SNAPSHOT-739 (0 KB)
· TrMenu - 3.6.1 (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· XConomy - 2.26.3 (0 KB)
· nightcore - 2.7.5.1 (0 KB)
```

### 🔍 详细的描述

渐变色不能正常显示，Wiki 中给出的[示例](https://hhhhhy.gitbook.io/trmenu-v3/usage/colors#jian-bian)如下：
```
Usage:
<gradient(or 'gradient')#<speed(ignorable)>:<hex range>>This is a Gradient, It's are beautifully! Do U like it?<loop(or 'l')>

E.g:
<g#2:#ffffff:#bbbbbb>text<l>
<g#2:#ffffff:#bbbbbb:#cccccc:#777777>text<l>
<g:#ffffff:#bbbbbb>text<l>
```
经过多次尝试，注意到以下问题：
- title 的渲染：
  1. `<g:#ff87cf:#fff5e1>test<l>` 未能正常渲染为渐变色（见图 3，与 wiki 不符）
  2. `<g:#ff87cf:#fff5e1>test` 情况类似（图 1）
  3. `<g:#ff87cf:#fff5e1>test</g>` 渲染为渐变色，但是 `</g>` 被当作文本一起渲染了（图 2）
- lore 的渲染：只要以 `<g:#ff87cf:#fff5e1>` 开头，就会渲染为渐变色，但是结尾的 `</g>`, `<l>` 都不能正常识别，被当作文本一起渲染。（与 wiki 不符）

![图1](https://github.com/user-attachments/assets/348d82b2-a335-4604-8d31-1f110ddeef09)

![图2](https://github.com/user-attachments/assets/d0adc310-ff0e-446d-a016-5a601f952b6b)

![图3](https://github.com/user-attachments/assets/d8e5966d-8a9e-480a-ad6c-8a59aafec17b)

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```
# Title: '<g:#ff87cf:#fff5e1>test'      # 第一张图
Title: '<g:#ff87cf:#fff5e1>test</g>'    # 第二张图
# Title: '<g:#ff87cf:#fff5e1>test<l>'   # 第三张图

Layout:
  - 'A        '

Bindings:
  Commands:
    - 'test'

Icons:
  'A':
    display:
     material: 'Grass Block'
     name: ' '
     lore:
       - '<g:#ff87cf:#fff5e1>text<l>'
       - '<g:#ff87cf:#fff5e1>text'
       - '<g:#ff87cf:#fff5e1>text</g>'
```
