### ISSUE TITLE
[问题]: 菜单内多次调用同一内置函数会导致传参混乱

### ISSUE THREAD

**Issue by Bronya256** [CoderKuo/TrMenu#180]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2025-06-18 17:43:41)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Paper-196 (MC: 1.20.1) (1.20.1-R0.1-SNAPSHOT)
| Java version: 21.0.5

| TrMenu: 3.6.4
Installed Plugins: 
· Adyeshach - 2.0.12 (0 KB)
· AfricanOpenBox - 1.0 (0 KB)
· AnimatedScoreboard - 0.3.6 (0 KB)
· AntiBuild - 1.3.2-SNAPSHOT (0 KB)
· AntiDropPlus - 1.2.3 (0 KB)
· AntiSeedCracker - 1.0 (0 KB)
· ArmorStandEdit - 2.1.2 (0 KB)
· AttributePlus - 3.3.3.0 (0 KB)
· Atziluth - 2.0.58 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2576 (0 KB)
· BKCommonLib - 1.21.1-v1 (0 KB)
· Banker - 1.3.3 (0 KB)
· CMI - 9.7.9.3 (0 KB)
· CMIEInjector - 1.0.2.4 (0 KB)
· CMILib - 1.5.2.9 (0 KB)
· Chemdah - 1.1.15 (0 KB)
· ChemdahExpansion - 1.0.7 (0 KB)
· Citizens - 2.0.32-SNAPSHOT (build 3208) (0 KB)
· CoreProtect - 22.4 (0 KB)
· CrackShot - 0.98.11 (0 KB)
· CrackShotPlus - 1.106 (0 KB)
· Denizen - 1.2.8-SNAPSHOT (build 1794-REL) (0 KB)
· EasyArmorStands - 2.5.0 (0 KB)
· FastAsyncWorldEdit - 2.9.2 (0 KB)
· GMusic - 1.0.0 (0 KB)
· GuoItemLoreCommand - 2.1 (0 KB)
· HeadDatabase - 4.21.1 (0 KB)
· HolographicDisplays - 3.0.4 (0 KB)
· Law - 2.4.0 (0 KB)
· LeatherColorizer - 1.2 (0 KB)
· LibsDisguises - 11.0.3 (0 KB)
· LightCleaner - 1.19.3-v1 (0 KB)
· LimitPillagers - 2.14.0 (0 KB)
· LuckPerms - 5.4.154 (0 KB)
· Multiverse-Core - 4.3.14 (0 KB)
· MythicCrucible - 2.1.0 (0 KB)
· MythicMobs - 5.7.2-${CI_COMMIT_SHORT_SHA} (0 KB)
· MythicMobsExtension - 1.758-SNAPSHOT (0 KB)
· NBTAPI - 2.14.1 (0 KB)
· NeigeItems - 1.21.18 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· PlayerTask - 2.4.5 (0 KB)
· ProtocolLib - 5.3.0 (0 KB)
· QiLingSuitPlugin - 1.0.5-BETA (0 KB)
· Residence - 5.1.6.5 (0 KB)
· RubbishMenu - 1.4.25 (0 KB)
· SbPlaceholder - 1.0-SNAPSHOT (0 KB)
· ScriptBlockPlus - 2.3.2 (0 KB)
· Shopkeepers - 2.22.3 (0 KB)
· TrChat - 2.2.2 (0 KB)
· TrMenu - 3.6.4 (0 KB)
· TreasureChest - 8.5 (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· ViaBackwards - 5.2.2-SNAPSHOT (0 KB)
· ViaVersion - 5.2.2-SNAPSHOT (0 KB)
· XgpEquipmentSlot - 1.1.2 (0 KB)
· goBrush - 3.8.0-87 (0 KB)
· goPaint - 3.1.0-97 (0 KB)
· packetevents - 2.7.1+91730fdb4-SNAPSHOT (0 KB)
· spark - 1.10.124 (0 KB)
```

### 🔍 详细的描述

在多次调用一个简化lore文本的函数（该函数返回文本应为固定且只与当前函数的传参有关）后，发现传入参数会彼此混乱，导致原本固定的文本会变化并混乱起来

表现为gif图中的图标lore理论是固定不变的，但是此时却变化起来

![Image](https://github.com/user-attachments/assets/c875cf31-16f9-44b8-bdb9-d6dcde4a368e)

### 🗄 服务端日志

无报错

### ⚙ 配置文件

```yml
Title:
  - '          test'

Title-Update: -1

Layout:
  - - '####A####'
    - '         '
    - '  B C    '
    - '         '
    - '         '
    - '#########'
  
#
# 图标
#
Icons:
  '#':
    update: [ -1, 10, -1, -1 ]
    display:
      material: Gray Stained Glass Pane
      name: [ '&7边界', '&7边&8界', '&8边界','&8&k边界' ]
    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
  C:
    update: 20
    display:
      material: oak_leaves
      name: '&f/// &2测试啊恩 &f///'
      lore:
      - ''
      - '${loreCheck_3_属性点_test11111}'
      - ''
      - '${loreCheck_3_属性点_test11111}'
    actions:
      all: 
        - 'close'
  B:
    update: 20
    display:
      material: oak_leaves
      name: '&f/// &2测试啊恩 &f///'
      lore:
      - ''
      - '${loreCheck_3_属性点_test2222}'
      - ''
      - '${loreCheck_3_属性点_test11222}'
    actions:
      all: 
        - 'close'
Functions:
  loreCheck: |-
    function loreCheck()
    {
      // 针对cmi用户元数据的检查
      // 传入参数 args0是预定数额，args1是指定的键值对(输入key返回value)，args2是显示的文字
      var arg1 = 0 + varInt("%cmi_user_meta_" + args[1] + "%");
      var returnStr = " &f  ";
      if( arg1 >= parseInt(args[0]) )
      {
        returnStr += "&a&l✔&r " + args[2] + " &7(&a" + arg1 + "&7/" + args[0] + ")";
      }
      else
      {
        returnStr += "&c✘&r " + args[2] + " &7(&a" + arg1 + "&7/" + args[0] + ")";
      }
      
      return returnStr;
    }
    loreCheck();
```
