### ISSUE TITLE
[Bug]: 玩家在执行指令时离线，触发的BUG

### ISSUE THREAD

**Issue by SakuraLeon** [CoderKuo/TrMenu#79]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

Save New Duplicate & Edit Just Text Discord

TrMenu Dump Information (Date: 2024-07-12 16:22:44)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Purpur-2062 (MC: 1.20.1) (1.20.1-R0.1-SNAPSHOT)
| Java version: 17.0.10

| TrMenu: 3.3.2g
Installed Plugins: 
· AlonsoTags - 2.0.7-BETA (0 KB)
· AnvilBlacklist - 1.1 (0 KB)
· AnvilFixer - 1.0-SNAPSHOT (0 KB)
· AttributeHider - 6.0.3 (0 KB)
· AutoResetWorld - 1.0 (0 KB)
· AyCore - 1.2.2-BETA (0 KB)
· BanIt - 1.1.5 (0 KB)
· Banker - 1.2.7 (0 KB)
· BattlePass - 4.3.7 (0 KB)
· BattleStatus - 1.0-SNAPSHOT (0 KB)
· BetterStructures - 1.6.8 (0 KB)
· BlueSlimeCore - 2.9.4.402 (0 KB)
· BungeeTabListPlus - 3.6.4 (0 KB)
· CMI - 9.6.9.6 (0 KB)
· CMILib - 1.4.4.4 (0 KB)
· ChestProtect - 5.11.11 (0 KB)
· ChestSort - 13.6.5 (0 KB)
· Citizens - 2.0.32-SNAPSHOT (build 3179) (0 KB)
· CitizensCMD - 2.6.12 (0 KB)
· ClueScrolls - 4.9.0 (0 KB)
· CombatPets - 1.0.25 Reborn Beta (0 KB)
· CommandWhitelist - 1.2.3 (0 KB)
· ConsoleSpamFix - 1.9.0 (0 KB)
· CustomCrops - 3.3.1.4 (0 KB)
· CustomFishing - 2.1.3.1 (0 KB)
· CustomJoinMessages - 16.0.0 (0 KB)
· CustomJsonMessage - 1.0-M1 (0 KB)
· Deenchanter - 1.0.0 (0 KB)
· DeluxeMenus - 1.13.7-Release (0 KB)
· DisablePistonFarming - 0.3 (0 KB)
· EcoEnchants - 12.12.0 (0 KB)
· Elevator - 3.13.0 (0 KB)
· EnchantUI - 1.0.0 (0 KB)
· EnchantmentSlots - 2.5.0 (0 KB)
· EternalTags - 1.2.1 (0 KB)
· ExploitFixer - 2.6.0 (0 KB)
· F-Command - 2.5.3 (0 KB)
· FastAsyncWorldEdit - 2.9.0 (0 KB)
· FlipCard - 2.5.3 (0 KB)
· FlyEnergy - 1.0.0 (0 KB)
· Freeze - 2.5.0.165 (0 KB)
· FunnyEnchantBook - 1.0.0 (0 KB)
· GPS - 2.19.27 (0 KB)
· GeminiCustomizedAutoDurability - 1.1.0 (0 KB)
· Gizmo - 1.2.1 (0 KB)
· GrScriptBlock - 1.1.0 (0 KB)
· Gunging_Ootilities_Plugin - 1.10.9 (0 KB)
· GuoItemLoreCommand - 2.1 (0 KB)
· HMCCosmetics - 2.7.2 (0 KB)
· HamsterAPI - 0.2.4 (0 KB)
· HeadDatabase - 4.17.0 (0 KB)
· HibiscusCommons - 0.3.1 (0 KB)
· HolographicDisplays - 3.0.4 (0 KB)
· HuskHomes - 4.5 (0 KB)
· HuskHomesGUI - 2.3 (0 KB)
· HybridServerAPI - 1.0.3 (0 KB)
· ILoreEdit - 2.5.1 (0 KB)
· Images - 2.3.1 (0 KB)
· InvBackup - 1.0.0 (0 KB)
· InvSync - 2.2.6-SNAPSHOT (0 KB)
· InventoryCopy - 1.0-SNAPSHOT (0 KB)
· ItemNBTEdit - 1.2.3 (0 KB)
· ItemStrengthen - 1.0-SNAPSHOT (0 KB)
· ItemsAdder - 3.5.0c-r4 (0 KB)
· JellyLib - 1.0-SNAPSHOT (0 KB)
· JulySafe - 4.0.7 (0 KB)
· KcSyncCommand-spigot - 1.0.3 (0 KB)
· LM_Items - 1.2.11 (0 KB)
· LegendaryDailyShop - 2.1.5 (0 KB)
· LibsDisguises - 10.0.40 (0 KB)
· LiteSignIn - 1.6.1.1 (0 KB)
· LoneLibs - 1.0.25 (0 KB)
· LuckPerms - 5.4.137 (0 KB)
· MMOCore - 1.12.1-SNAPSHOT (0 KB)
· MMOItems - 6.10-SNAPSHOT (0 KB)
· MMOPlayerStats - 1.0.0 (0 KB)
· MMobStatistics - 1.0-SNAPSHOT (0 KB)
· ModelEngine - R3.1.9 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· MyBind - 1.3 (0 KB)
· MyVariable - 1.0.0 (0 KB)
· MythicDungeons - 1.2.2-SNAPSHOT (0 KB)
· MythicLib - 1.6.2-SNAPSHOT (0 KB)
· MythicLibreforge - 1.3.1 (0 KB)
· MythicMobs - 5.5.2-SNAPSHOT-2225ead2 (0 KB)
· NBTAPI - 2.12.2 (0 KB)
· NeigeItems - 1.17.22 (0 KB)
· NexEngine - 2.2.12 (0 KB)
· NoFishRepair - 1.0.0 (0 KB)
· NyEconomy - 1.7.1-SNAPSHOT (0 KB)
· ODailyQuests - 2.2.3 (0 KB)
· OPWhitelist - 1.0.2 (0 KB)
· OnlineReward - 1.7.1-SNAPSHOT (0 KB)
· Orebfuscator - 5.4.3 (0 KB)
· PackPlaceholderAPI - 1.0-SNAPSHOT (0 KB)
· Parties - 3.2.12 (0 KB)
· PhantomDisabler - 1.1 (0 KB)
· PixelWorldPro - 1.3.3 (0 KB)
· PlaceholderAPI - 2.11.3 (0 KB)
· PlaceholderAction - 1.0-SNAPSHOT (0 KB)
· PlayerBroadcast - 1.0-SNAPSHOT (0 KB)
· PlayerLottery - 1.0-SNAPSHOT (0 KB)
· PlayerMount - 1.0.0 (0 KB)
· PlayerPets - 1.0.0 (0 KB)
· PlayerPoints - 3.2.6 (0 KB)
· PlayerWarp - 1.3.4 (0 KB)
· PlayerWorldEdit - 1.0-SNAPSHOT (0 KB)
· PlugManX - 2.3.4 (0 KB)
· ProtocolLib - 5.0.0 (0 KB)
· ProtocolStringReplacer - 2.19.3 (0 KB)
· Purse - 1.0 (0 KB)
· Quest - 1.0-SNAPSHOT (0 KB)
· QuickShop-Hikari - 5.2.0.5 (0 KB)
· RPGInventory - 1.8.1-SNAPSHOT (0 KB)
· RandomAndPapi - 1.0.2 (0 KB)
· RealisticSeasons - 10.5.8 (0 KB)
· RestrictedShop - 1.0.0 (0 KB)
· RoseLoot - 1.2.12 (0 KB)
· ScriptBlockPlus - 2.2.8 (0 KB)
· ServerMarket - 2.6.1 (0 KB)
· SignRecharge - 1.0-SNAPSHOT (0 KB)
· SkBee - 3.5.4 (0 KB)
· Skript - 2.8.7 (0 KB)
· StoryBoard - 1.0-SNAPSHOT (0 KB)
· StoryMount - 1.0-SNAPSHOT (0 KB)
· StoryPet - 1.0-SNAPSHOT (0 KB)
· StorySpawner - 1.0-SNAPSHOT (0 KB)
· StroyVault - 1.0-SNAPSHOT (0 KB)
· TAB - 4.1.2 (0 KB)
· TAB-Bridge - 5.0.3 (0 KB)
· TrChat - 2.0.8 (0 KB)
· TrMenu - 3.3.2g (0 KB)
· TradeSystem - 2.3.2 (0 KB)
· UltimateShop - 1.12.6 (0 KB)
· UnbreakableEX - 1.0 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.8.1 (0 KB)
· ViaVersion - 4.8.1 (0 KB)
· VoidFramework-Bukkit - 2.1.3 (0 KB)
· VoidGenerator - 1.4.2 (0 KB)
· WorldBorder - 1.8.5 (0 KB)
· WorldGuard - 7.0.9-beta1+2249-223b80c (0 KB)
· WorldLimit - 1.20 (0 KB)
· XConomy - 2.25.5 (0 KB)
· XinxinBotApi - 2.0.4-SNAPSHOT (0 KB)
· YukiNoaAPI - 1.0.0 (0 KB)
· ajLeaderboards - 2.7.0 (0 KB)
· chestcommand - 1.0-SNAPSHOT (0 KB)
· eco - 6.71.4 (0 KB)
· encommand - 1.0-SNAPSHOT (0 KB)
· healfeed - 1.0 (0 KB)
· libreforge - 4.65.0 (0 KB)
· spark - 1.10.74 (0 KB)

### 🔍 Detailed description

```
1.  触发方式: 玩家在游戏中，通过菜单内的延迟actions指令，在执行时下线，即可触发
2. 触发方式: 玩家离线后，如菜单的actions还在为该玩家执行指令，即可触发
3. 触发后，玩家再次上线，重新打开菜单后，无法使用任何功能，不会显示icon的内容
4. 此问题会导致 icons无法正常显示,  action无法正常使用，插件内部的权限无法正常判断
```

### 🗄 Server log

```

```

### ⚙ Configurations

```

```

**Comment by aeroidesdev** [comment]
日志和配置文件

**Comment by SakuraLeon** [comment]
> 日志和配置文件

Options:
  # High, Normal, Low
  Running-Performance: Normal
  Multi-Thread: true
  Async-Load-Menus: true
  Static-Inventory:
    Java: false
    Bedrock: false
  Packet-Inventory:
    Create-Id: false

  Placeholders:
    JavaScript-Parse: false
    Jexl-Parse: false

Language:
  Default: 'zh_CN'
  # Parse the provided text as player language
  # Leave it blank to use player locale instead
  Player: ''
  CodeTransfer:
    zh_hans_cn: 'zh_CN'
    zh_hant_cn: 'zh_TW'
    en_ca: 'en_US'
    en_au: 'en_US'
    en_gb: 'en_US'
    en_nz: 'en_US'
    
Database:
  # Local: SQLITE
  # External: SQL, MONGODB
  Method: SQLITE
  Type:
    SQLite:
      file-name: data
      table: npc
    SQL:
      host: localhost
      port: 3307
      user: root
      password: root
      database: test
      table: trmenu_user_data
    MongoDB:
      client: 'mongodb://localhost:3307'
      database: trixey
      collection: trplugins.menu
  Index:
    # UUID, USERNAME
    Player: USERNAME

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Using-Component: false
  Inputer:
    Cancel-Words:
      #- 'cancel|quit|end'
      - '(?i)cancel|quit|exit|end|stop'
      - 'q'
  Kether:
    Allow-Tolerance-Parser: true


Shortcuts:
  Offhand: [ ]
  Sneaking-Offhand:
    - condition: 'perm *trmenu.shortcut'
      execute: 'open: Example'
      deny: 'return'
  Right-Click-Player: [ ]
  Sneaking-Right-Click-Player: 'open: 查看玩家信息'
  PlayerInventory-Border-Left: [ ]
  PlayerInventory-Border-Right: [ ]
  PlayerInventory-Border-Middle: [ ]

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'


Scripts:
  Export-Hook-Plugin: true
  Mozilla-Compat: true
  Binding-Map:

**Comment by SakuraLeon** [comment]
> 日志和配置文件

在触发后，后台并无任何错误的log，会直接执行actions里面的内容（不会执行title, message，只会执行CONSOLE这种）
并且icons也无法正常显示
导致
例: 玩家在触发这种状态后，进入到礼包系统，无视icons（根据权限判断玩家是否已领取），然后重复执行conosle的内容

**Comment by TheFloodDragon** [comment]
请给出可以复现此操作的菜单配置文件（不是settings.yml或者conig.yml这类）

**Comment by TheFloodDragon** [comment]
另外：“玩家退出后，sleep当中的脚本动作仍会执行” 属于是特性，不会修复，请尽可能避免Sleep操作（会阻塞线程）

**Comment by SakuraLeon** [comment]
> 请给出可以复现此操作的菜单配置文件（不是settings.yml或者conig.yml这类）

#&3&lTip &7| &f갃
Title: ' '
Layout:
    - '#########'
    - '####1####'
    - '#########'
# 菜单选项（全都是可选的，无需配置）
Events:
  Open:
  - 'sound: UI_LOOM_TAKE_RESULT'
  Close:
  - 'sound: BLOCK_CHEST_CLOSE-1-2'
Options:
  # 本菜单强制需要以下 PlaceholderAPI 拓展，若无将自动下载
  Depend-Expansions: []
  # 锁定玩家背包 (Default: true)
  Lock-Player-Inv: true
  # 每次刷新图标时都更新玩家背包
  # [!] 不推荐开启. 除非你是低版本 Minecraft 服务器，且需要流畅的动画效果
  Update-Inventory: false
Icons:
  '#':
    display:
      material: 'BLACK_STAINED_GLASS_PANE'
      name: '&f'
  '1':
    update: 20
    display:
      material: 'CHEST'
      name: '&{#e8b1b1}签到专区'
      lore:
      - ''
      - ' &{#F0FFFF}礼包内容: '
      - ''
      - '   &f钻石x64'
      - ''
      - "&8→ &f点击左键领取"
      - ''
    actions:
      ALL:
        - 'close'
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-0'  
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e3s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e2s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e1s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&e礼包已发放` 35 20 35'
        
        - 'console: lp user %player_name% perm set 已领取.礼包'
            
        - 'console: give %player_name% DIAMOND 64'
            
        - "tell: &f "
        - "tell: &f 礼包已发放, 请背包中查看"
        - "tell: &f "
    icons:
      - condition: 'perm *已领取.礼包'
        display:
          material: 'BARRIER'
          name: '&{#e8b1b1}签到专区'
          lore:
            - ''
            - ' &{#F0FFFF}礼包内容: '
            - ''
            - '   &f钻石x64'
            - ''
            - "&8→ &c已领取"
            - ''

**Comment by SakuraLeon** [comment]
> 请给出可以复现此操作的菜单配置文件（不是settings.yml或者conig.yml这类）

```
#&3&lTip &7| &f갃
Title: ' '
Layout:
    - '#########'
    - '####1####'
    - '#########'
# 菜单选项（全都是可选的，无需配置）
Events:
  Open:
  - 'sound: UI_LOOM_TAKE_RESULT'
  Close:
  - 'sound: BLOCK_CHEST_CLOSE-1-2'
Options:
  # 本菜单强制需要以下 PlaceholderAPI 拓展，若无将自动下载
  Depend-Expansions: []
  # 锁定玩家背包 (Default: true)
  Lock-Player-Inv: true
  # 每次刷新图标时都更新玩家背包
  # [!] 不推荐开启. 除非你是低版本 Minecraft 服务器，且需要流畅的动画效果
  Update-Inventory: false
Icons:
  '#':
    display:
      material: 'BLACK_STAINED_GLASS_PANE'
      name: '&f'
  '1':
    update: 20
    display:
      material: 'CHEST'
      name: '&{#e8b1b1}签到专区'
      lore:
      - ''
      - ' &{#F0FFFF}礼包内容: '
      - ''
      - '   &f钻石x64'
      - ''
      - "&8→ &f点击左键领取"
      - ''
    actions:
      ALL:
        - 'close'
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-0'  
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e3s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e2s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e1s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&e礼包已发放` 35 20 35'
        
        - 'console: lp user %player_name% perm set 已领取.礼包'
            
        - 'console: give %player_name% DIAMOND 64'
            
        - "tell: &f "
        - "tell: &f 礼包已发放, 请背包中查看"
        - "tell: &f "
    icons:
      - condition: 'perm *已领取.礼包'
        display:
          material: 'BARRIER'
          name: '&{#e8b1b1}签到专区'
          lore:
            - ''
            - ' &{#F0FFFF}礼包内容: '
            - ''
            - '   &f钻石x64'
            - ''
            - "&8→ &c已领取"
            - ''
```

**Comment by SakuraLeon** [comment]
> 日志和配置文件

你好，这是我的菜单配置文件
直接点击执行，然后马上离线，重新上线以后就可以无视icons，重复执行了
```
#&3&lTip &7| &f갃
Title: ' '
Layout:
    - '#########'
    - '####1####'
    - '#########'
# 菜单选项（全都是可选的，无需配置）
Events:
  Open:
  - 'sound: UI_LOOM_TAKE_RESULT'
  Close:
  - 'sound: BLOCK_CHEST_CLOSE-1-2'
Options:
  # 本菜单强制需要以下 PlaceholderAPI 拓展，若无将自动下载
  Depend-Expansions: []
  # 锁定玩家背包 (Default: true)
  Lock-Player-Inv: true
  # 每次刷新图标时都更新玩家背包
  # [!] 不推荐开启. 除非你是低版本 Minecraft 服务器，且需要流畅的动画效果
  Update-Inventory: false
Icons:
  '#':
    display:
      material: 'BLACK_STAINED_GLASS_PANE'
      name: '&f'
  '1':
    update: 20
    display:
      material: 'CHEST'
      name: '&{#e8b1b1}签到专区'
      lore:
      - ''
      - ' &{#F0FFFF}礼包内容: '
      - ''
      - '   &f钻石x64'
      - ''
      - "&8→ &f点击左键领取"
      - ''
    actions:
      ALL:
        - 'close'
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-0'  
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e3s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e2s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&7((( &c&o礼包领取中, 正在为您储存数据 &7)))` `&7发放倒计时: &e1s` 35 20 35'
        - 'sound: ENTITY_ENDER_DRAGON_FLAP-1-2'
        - 'DELAY: 20'
        
        - 'title: `&e礼包已发放` 35 20 35'
        
        - 'console: lp user %player_name% perm set 已领取.礼包'
            
        - 'console: give %player_name% DIAMOND 64'
            
        - "tell: &f "
        - "tell: &f 礼包已发放, 请背包中查看"
        - "tell: &f "
    icons:
      - condition: 'perm *已领取.礼包'
        display:
          material: 'BARRIER'
          name: '&{#e8b1b1}签到专区'
          lore:
            - ''
            - ' &{#F0FFFF}礼包内容: '
            - ''
            - '   &f钻石x64'
            - ''
            - "&8→ &c已领取"
            - ''
```

**Comment by TheFloodDragon** [comment]
> > 日志和配置文件
> 
> 你好，这是我的菜单配置文件 直接点击执行，然后马上离线，重新上线以后就可以无视icons，重复执行了
> 

请在icons下的图标配置独立加个actions
如：
```
icons:
  - condition: 条件
     ....其它东西
     actions:
         - 'sound BLOCK_NOTE_BLOCK_BIT-1-0'
```
我记得子图标貌似会默认继承父图标的动作
